## 2020 ~ 2024년의 ESG 데이터 (한국ESG기준원)
- https://www.cgs.or.kr/business/esg_tab04.jsp#listPanel
    - 칼럼명( 기업명 / 기업코드 / ESG구조 / 환경 / 사회 / 지배구조 )

In [2]:
import pandas as pd
import numpy as np

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_9248\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
# esg data 불러오기
df = pd.read_excel('esg_data.xlsx')
df1 = df.copy()

C:\Users\SAMSUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [4]:
# NO, ESG 등급조정, 환경 등급조정, 사회 등급조정, 지배구조 등급 조정 제거
df1.drop(
    columns={
        'NO','ESG 등급조정','환경 등급조정','사회 등급조정','지배구조 등급조정'
    }
    , inplace=True
)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5117 entries, 0 to 5116
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기업명     5112 non-null   object
 1   기업코드    5112 non-null   float64
 2   ESG등급   5112 non-null   object
 3   환경      5112 non-null   object
 4   사회      5112 non-null   object
 5   지배구조    5112 non-null   object
 6   평가년도    5112 non-null   float64
dtypes: float64(2), object(5)
memory usage: 280.0+ KB

In [6]:
flag = df1[df1.isnull().all(axis=1)].index

In [7]:
flag
# [649, 775, 1921, 2397, 2667] -> 2667은 행 삭제

Index([649, 775, 1921, 2397, 2667], dtype='int64')

In [8]:
# 검색
# 649 : SK이노베이션 , 2021년도로 수정 
# df1.loc[648:650,]
df1.loc[649,'기업명'] = 'SK이노베이션'
df1.loc[649,'기업코드'] = '96770.0'
df1.loc[649,'평가년도'] = 2021

# 775 : 경동나비엔, 2021년도로 수정
# df1.loc[774:776,]
df1.loc[775,'기업명'] = '경동나비엔'
df1.loc[775,'기업코드'] = '9450.0'
df1.loc[775,'평가년도'] = 2021

# 1921 : 백광산업, 2021년도로 수정
# df1.loc[1920:1923,]
df1.loc[1921,'기업명'] = '백광산업'
df1.loc[1921,'기업코드'] = '1340.0'
df1.loc[1921,'평가년도'] = 2021

# 2397 : 세아베스틸지주로 이름 변경(2396도) 
# df1.loc[2396:2399,]
df1.loc[2396:2398,'기업명'] = '세아베스틸지주'
df1.loc[2397,'기업코드'] = '1430.0'
df1.loc[2397,'평가년도'] = 2021

# 2667 행 삭제 -> 어떤 회사인지 모름 
df1 = df1.drop(index=2667)

# 확인 
df1[df1.isnull().all(axis=1)]

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_9248\3295909227.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '96770.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df1.loc[649,'기업코드'] = '96770.0'

Empty DataFrame
Columns: [기업명, 기업코드, ESG등급, 환경, 사회, 지배구조, 평가년도]
Index: []

In [9]:
# 평가년도 int로 바꾸기
df1['평가년도'] = df1['평가년도'].astype('float').astype('int')

In [12]:
# D등급 1점, C등급 2점, B등급 3점, B+등급 4점, A등급 5점, A+등급 6점
# 등급없음 NAN 처리 
# df1['ESG등급'].value_counts()
# df1['환경'].value_counts()
# df1['사회'].value_counts()
# df1['지배구조'].value_counts()
grade_map = {
    'D' : 1,
    'C' : 2,
    'B' : 3,
    'B+' : 4,
    'A' : 5,
    'A+' : 6,
    '등급없음' : 0
}

# ESG 등급 점수화
df1['ESG등급'] = df1['ESG등급'].map(grade_map)
df1['환경'] = df1['환경'].map(grade_map)
df1['사회'] = df1['사회'].map(grade_map)
df1['지배구조'] = df1['지배구조'].map(grade_map)

In [18]:
df1.head()

      기업명     기업코드  ESG등급   환경   사회  지배구조  평가년도
0  AJ네트웍스  95570.0    3.0  1.0  3.0   3.0  2020
1  AJ네트웍스  95570.0    3.0  1.0  3.0   3.0  2021
2  AJ네트웍스  95570.0    4.0  2.0  4.0   4.0  2022
3  AJ네트웍스  95570.0    4.0  2.0  5.0   4.0  2023
4  AJ네트웍스  95570.0    4.0  2.0  5.0   4.0  2024

In [207]:
# 총 1338개의 unique한 기업명이 있다
list1 = df1['기업명'].unique().tolist()
# 리스트를 데이터프레임으로 변환
df_list = pd.DataFrame(list1,columns=['기업명'])
# CSV 파일로 저장
df_list.to_csv("기업명리스트.csv",index=False, encoding='utf-8-sig')

In [ ]:
# 금융업 제거 (118개 기업 제거) -> df1 5112개 행 -> df2 4627개 행(485개 제거)  
# 금융업(은행, 보험, 증권 등)은 일반 제조업이나 서비스업과는 
# 전혀 다른 회계 기준과 수익구조를 가지고 있습니다.
keywords = ['보험','은행','증권','지주','투자','캐피탈','NICE']
list2 = [name for name in df1['기업명'].unique() if any(keyword in name for keyword in keywords)]
print(list2)
# len(list2)
df2 = df1.copy()
for i in df2.index:
    if df2.loc[i,'기업명'] in list2:
        df2 = df2.drop(i)

['BNK금융지주', 'BNK캐피탈', 'DB금융투자', 'DB생명보험', 'DB손해보험', 'DB증권', 'DGB금융지주', 'DGB생명보험', 'JB금융지주', 'KB금융지주', 'KB라이프생명보험', 'KB손해보험', 'KB캐피탈', 'KTB투자증권', 'LS증권', 'NH농협손해보험', 'NH투자증권', 'NICE', 'NICE평가정보', 'SK증권', 'iM금융지주', '경남은행', '광주은행', '교보생명보험', '교보증권', '국민은행', '기업은행', '농협금융지주', '농협생명보험', '농협은행', '다올투자증권', '대구은행', '대신증권', '라이나생명보험', '롯데손해보험', '롯데지주', '롯데캐피탈', '리더스 기술투자', '메리츠금융지주', '메리츠종금증권', '메리츠증권', '메리츠캐피탈', '메리츠화재해상보험', '메이슨캐피탈', '메트라이프생명보험', '미래에셋벤처투자', '미래에셋증권', '미래에셋캐피탈', '부국증권', '부산은행', '산은캐피탈', '삼성증권', '삼성화재해상보험', '상상인증권', '서울보증보험', '성창기업지주', '세아베스틸지주', '세아제강지주', '신영증권', '신한금융투자', '신한라이프생명보험', '신한생명보험', '신한은행', '신한지주', '신한캐피탈', '신한투자증권', '아이비케이연금보험', '아이비케이캐피탈', '아이비케이투자증권', '아주IB투자', '에이비엘생명보험', '에이아이에이생명보험', '엔에이치농협캐피탈', '우리금융지주', '우리금융캐피탈', '우리기술투자', '우리은행', '유안타증권', '유진증권', '유진투자증권', '유화증권', '이베스트투자증권', '전북은행', '제이비우리캐피탈', '제주은행', '케이디비생명보험', '케이뱅크은행', '케이비라이프생명보험', '케이비생명보험', '케이비증권', '케이비캐피탈', '코리아에셋투자증권', '큐캐피탈', '키움증권', '푸르덴셜생명보험', '푸본현대생명보험', '하나금융지주', '하나금융투자', '하나생명보험', '하나은행', '하나증권', '하나캐피탈', '하림지주', '하이투자증권', '한국금융지주', '한국스탠다드차타드은행', '한국씨티은행', '한국카카오은행', '한국캐피탈', '한국투자증권', '한국투자캐피탈', '한양증권', '한화손해보험', '한화투자증권', '현대중공업지주', '현대차증권', '현대캐피탈', '흥국생명보험']

#### 엑셀로 위의 작업 완료
## 다시불러오자

In [28]:
import pandas as pd

df = pd.read_excel('data.xlsx', converters={'기업명': str, '기업코드': str})
df.head()

      기업명    기업코드  ESG등급   환경   사회  지배구조  평가년도
0  AJ네트웍스  095570    3.0  1.0  3.0   3.0  2020
1  AJ네트웍스  095570    3.0  1.0  3.0   3.0  2021
2  AJ네트웍스  095570    4.0  2.0  4.0   4.0  2022
3  AJ네트웍스  095570    4.0  2.0  5.0   4.0  2023
4  AJ네트웍스  095570    4.0  2.0  5.0   4.0  2024

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4602 entries, 0 to 4601
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기업명     4602 non-null   object
 1   기업코드    4602 non-null   object
 2   ESG등급   4602 non-null   float64
 3   환경      4602 non-null   float64
 4   사회      4602 non-null   float64
 5   지배구조    4602 non-null   float64
 6   평가년도    4602 non-null   int64
dtypes: float64(4), int64(1), object(2)
memory usage: 251.8+ KB