In [1]:
import pandas as pd

## esg 평가데이터 불러오기

In [53]:
# 한국 ESG 기준원 데이터 불러오기 
# 10990개 
evaluate_df = pd.read_excel('evaluate_data.xlsx',dtype={
    '기업코드' : str
})
evaluate_df.head()

c:\Users\eogks\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NO,기업명,기업코드,ESG등급,환경,사회,지배구조,평가년도,ESG 등급조정,환경 등급조정,사회 등급조정,지배구조 등급조정
0,10990.0,AJ네트웍스,095570,미공개,미공개,미공개,C,2016.0,NaN,NaN,NaN,NaN
1,10989.0,AJ네트웍스,095570,미공개,미공개,미공개,B,2017.0,NaN,NaN,NaN,NaN
2,10988.0,AJ네트웍스,095570,미공개,미공개,미공개,C,2018.0,NaN,NaN,NaN,NaN
3,10987.0,AJ네트웍스,095570,B,미공개,B,B,2019.0,NaN,NaN,NaN,NaN
4,10986.0,AJ네트웍스,095570,B,D,B,B,2020.0,NaN,NaN,NaN,NaN

In [54]:
# ESG 데이터 컬럼확인
evaluate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10990 entries, 0 to 10989
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NO         10985 non-null  float64
 1   기업명        10985 non-null  object
 2   기업코드       10985 non-null  object
 3   ESG등급      10985 non-null  object
 4   환경         10985 non-null  object
 5   사회         10985 non-null  object
 6   지배구조       10985 non-null  object
 7   평가년도       10985 non-null  float64
 8   ESG 등급조정   167 non-null    object
 9   환경 등급조정    57 non-null     object
 10  사회 등급조정    277 non-null    object
 11  지배구조 등급조정  217 non-null    object
dtypes: float64(2), object(10)
memory usage: 1.0+ MB

In [55]:
# 기업명, 기업코드, ESG 등급, 환경, 사회, 지배구조, 평가년도 컬럼만 사용하자
ev_df = evaluate_df.drop(columns={
    'NO','ESG 등급조정','환경 등급조정','사회 등급조정','지배구조 등급조정'
})
ev_df.head()

      기업명    기업코드 ESG등급   환경   사회 지배구조    평가년도
0  AJ네트웍스  095570   미공개  미공개  미공개    C  2016.0
1  AJ네트웍스  095570   미공개  미공개  미공개    B  2017.0
2  AJ네트웍스  095570   미공개  미공개  미공개    C  2018.0
3  AJ네트웍스  095570     B  미공개    B    B  2019.0
4  AJ네트웍스  095570     B    D    B    B  2020.0

In [56]:
# 결측치 제거 (빈 행 5개 제거 -> 10985개)
ev_df = ev_df.dropna()
ev_df

          기업명    기업코드 ESG등급   환경   사회 지배구조    평가년도
0      AJ네트웍스  095570   미공개  미공개  미공개    C  2016.0
1      AJ네트웍스  095570   미공개  미공개  미공개    B  2017.0
2      AJ네트웍스  095570   미공개  미공개  미공개    C  2018.0
3      AJ네트웍스  095570     B  미공개    B    B  2019.0
4      AJ네트웍스  095570     B    D    B    B  2020.0
...       ...     ...   ...  ...  ...  ...     ...
10985    흥아해운  003280     D    D    C    D  2020.0
10986    흥아해운  003280     D    D    C    D  2021.0
10987    흥아해운  003280     C    C    B    C  2022.0
10988    흥아해운  003280     B    B   B+    B  2023.0
10989    흥아해운  003280     B    B   B+    B  2024.0

[10985 rows x 7 columns]

In [57]:
# 평가년도 확인 2012년은 제거 -> 706개 
# 2013년부터 ESG 등급체계 달라짐
# 10279개 행
ev_df = ev_df[~(ev_df['평가년도'] == 2012)]
ev_df
# ev_df.to_excel('ev_df_v1.xlsx')

          기업명    기업코드 ESG등급   환경   사회 지배구조    평가년도
0      AJ네트웍스  095570   미공개  미공개  미공개    C  2016.0
1      AJ네트웍스  095570   미공개  미공개  미공개    B  2017.0
2      AJ네트웍스  095570   미공개  미공개  미공개    C  2018.0
3      AJ네트웍스  095570     B  미공개    B    B  2019.0
4      AJ네트웍스  095570     B    D    B    B  2020.0
...       ...     ...   ...  ...  ...  ...     ...
10985    흥아해운  003280     D    D    C    D  2020.0
10986    흥아해운  003280     D    D    C    D  2021.0
10987    흥아해운  003280     C    C    B    C  2022.0
10988    흥아해운  003280     B    B   B+    B  2023.0
10989    흥아해운  003280     B    B   B+    B  2024.0

[10279 rows x 7 columns]

In [58]:
# ESG등급 등급없음 제거 -> 345개 제거 : 9934개 
ev_df = ev_df[~(ev_df['ESG등급'] == '등급없음')]

flag1 = (ev_df['ESG등급'] == '미공개')
flag2 = (ev_df['환경'] == '미공개')
flag3 = (ev_df['사회'] == '미공개')
flag4 = (ev_df['지배구조'] == '미공개')

# case 1
# ESG등급, 환경, 사회, 지배구조 모두 미공개면 제거 -> 18개 제거 : 9916개
# ev_df1 = ev_df[~(flag1 & flag2 & flag3 & flag4)]
# ev_df1 = ev_df.reset_index(drop=True)

# case 2
# ESG등급, 환경, 사회, 지배구조 하나라도 미공개면 제거 ->  4307개 제거 : 5627개
ev_df = ev_df[~(flag1 | flag2 | flag3 | flag4)]
ev_df = ev_df.reset_index(drop=True)

In [60]:
# 미공개 = 0, D = 1, C = 2, B = 3, B+ = 4, A = 5, A+ = 6 점으로 계량화
# map 함수는 Series에만 적용이 되기 때문에 여러개 열을 쓰고 싶을때는 applymap을 쓰자
mapping_dict = {
    '미공개' : 0,
    'D' : 1,
    'C' : 2,
    'B' : 3,
    'B+' : 4,
    'A' : 5,
    'A+' : 6,
    'S' : 7
}

# applymap에는 lambda를 필수로 써야한다 
# mapping_dict.get(키, 기본값)
ev_df[['ESG등급','환경','사회','지배구조']] = ev_df[['ESG등급','환경','사회','지배구조']].applymap(lambda x : mapping_dict.get(x, 0))

C:\Users\eogks\AppData\Local\Temp\ipykernel_15192\3886160781.py:16: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ev_df[['ESG등급','환경','사회','지배구조']] = ev_df[['ESG등급','환경','사회','지배구조']].applymap(lambda x : mapping_dict.get(x, 0))

In [ ]:
# float 이라서 int로 바꿔주자꿔주자
ev_df['평가년도'] = ev_df['평가년도'].astype('int')

In [63]:
# case 2 미공개 다 제거한 데이터로 평가 완료 
ev_df.to_excel('ev_df_case2.xlsx')

## 재무데이터 불러오기

In [103]:
# 재무데이터 불러오기
finance_df = pd.read_excel(
    'finance_data.xlsx',
    dtype={'거래소코드' : str},
    parse_dates=['[공통]설립일']
)
finance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28295 entries, 0 to 28294
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   회사명                               28295 non-null  object
 1   거래소코드                             28295 non-null  object
 2   회계년도                              28295 non-null  object
 3   자산(*)(IFRS)(천원)                   26395 non-null  float64
 4   자본(*)(IFRS)(천원)                   26395 non-null  float64
 5   부채(*)(IFRS)(천원)                   26395 non-null  float64
 6   영업활동으로 인한 현금흐름(간접법)(*)(IFRS)(천원)  26395 non-null  float64
 7   매출액(요약)(백만원)                      28198 non-null  float64
 8   [제조]      유형자산(*)(IFRS)(천원)       26156 non-null  float64
 9   [제조]      재고자산(*)(IFRS)(천원)       26156 non-null  float64
 10  [공통]설립일                           28295 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(7), object(3)
memory usage: 2.4+ MB

In [106]:
# 이름 바꾸기
finance_df.columns = ['기업명','기업코드','평가년도','자산','자본','부채','현금흐름','매출액','유형자산','재고자산','설립일']

In [ ]:
# 평가년도에서 앞쪽에 년도만 추출하고 int 형으로 변환
finance_df['평가년도'] = finance_df['평가년도'].str[0:4].astype(int)

# 설립일에서도 년도만 추출하고 int형으로 변환
finance_df['설립일'] = finance_df['설립일'].dt.year.astype(int)

In [ ]:
# 기업연령(AGE 변수 만들자, 2025에서 빼줌)
finance_df['기업연령'] = 2025 - finance_df['설립일']

# 설립일 컬럼 제거 
finance_df = finance_df.drop(columns={
    '설립일'
})

In [127]:
# 매출액 단위 맞춰주자 백만원단위라 천원단위로 바꿔야함 
# 1000곱하자
finance_df['매출액'] = finance_df['매출액'] * 1000

In [ ]:
# 두 DataFrame 간에 공통된 기업코드가 있는지 확인하려면..
# set(ev_df['기업코드']) & set(ev_df['기업코드'])
# set(ev_df['평가년도']) & set(ev_df['평가년도'])

# 기업코드와 평가년도 두개가 동시에 쌍을 이루어 같은게 있는지 확인하려면..

# set(zip(ev_df['기업코드'],ev_df['평가년도'])) & set(zip(finance_df['기업코드'],finance_df['평가년도']))

In [170]:
# finance_df의 기업코드 공백을 제거하자 
finance_df['기업코드'] = finance_df['기업코드'].replace(' ','',regex=True)

In [185]:
# ev_df와 병합하자 
merge_df = pd.merge(
    finance_df,
    ev_df[['기업코드','평가년도','ESG등급','환경','사회','지배구조']],
    how='left',
    on = ['기업코드','평가년도']
)


# 28295개 열에서 23167개 열 제거 : 5128개 행
merge_df = merge_df[~(merge_df['ESG등급'].isnull())]

In [ ]:
# 엘브이엠씨홀딩스(주), 기업코드 : 900140, 평가년도 : 2022 
# 위의 1개 재무데이터 없음 삭제처리 
merge_df = merge_df[~(merge_df['기업코드'] == '900140')]
merge_df = merge_df.reset_index(drop=True)
merge_df.to_excel('merge_df.xlsx')